// AUTO-GENERATED by tools/build-cdn.mjs for app version 2.0.0. Do not edit by hand.
//
// The copy of each remote baked into the host: which version the native build phases copied into
// the app, and that version's manifest, which React Native's fetch cannot read from the disk.

export const BUNDLED_VERSIONS: Record<string, Record<string, string>> = {
  ios: { listApp: '1.2.0', partyApp: '1.0.0' },
  android: { listApp: '1.2.0', partyApp: '1.0.0' },
};

export const EMBEDDED_MANIFESTS: Record<string, Record<string, unknown>> = {
  ios: {
    listApp: {
      id: 'listApp',
      name: 'listApp',
      metaData: {
        name: 'listApp',
        type: 'app',
        buildInfo: { buildVersion: '0.0.1', buildName: 'List' },
        remoteEntry: {
          name: 'listApp.container.js.bundle',
          path: '',
          type: 'global',
        },
        types: { path: '', name: '', zip: '', api: '' },
        globalName: 'listApp',
        pluginVersion: '2.9.0',
        publicPath: 'noop:///',
      },
      shared: [
        {
          id: 'listApp:@pokedex/contracts',
          name: '@pokedex/contracts',
          version: '3.3.0',
          singleton: true,
          requiredVersion: '^3.3.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_pokedex_contracts_dist_index_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@pokedex/ui',
          name: '@pokedex/ui',
          version: '1.0.13',
          singleton: true,
          requiredVersion: '^1.0.13',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_pokedex_ui_src_index_ts.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@react-native/assets-registry/path-support',
          name: '@react-native/assets-registry/path-support',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@react-native/assets-registry/registry',
          name: '@react-native/assets-registry/registry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@react-native/normalize-colors',
          name: '@react-native/normalize-colors',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@react-native/virtualized-lists',
          name: '@react-native/virtualized-lists',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@react-navigation/native-stack',
          name: '@react-navigation/native-stack',
          version: '7.18.6',
          singleton: true,
          requiredVersion: '^7.18.6',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-navigation_native-stack_lib_module_index_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@react-navigation/native',
          name: '@react-navigation/native',
          version: '7.3.14',
          singleton: true,
          requiredVersion: '^7.3.1',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-navigation_native_lib_module_index_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@reduxjs/toolkit',
          name: '@reduxjs/toolkit',
          version: '2.12.0',
          singleton: true,
          requiredVersion: '^2.12.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_reduxjs_toolkit_dist_redux-toolkit_modern_mjs.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:nativewind',
          name: 'nativewind',
          version: '4.2.6',
          singleton: true,
          requiredVersion: '^4.2.6',
          assets: {
            js: {
              async: [],
              sync: ['node_modules_nativewind_dist_index_js.chunk.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native-reanimated',
          name: 'react-native-reanimated',
          version: '4.6.0',
          singleton: true,
          requiredVersion: '^4.6.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-native-reanimated_src_index_ts.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native-safe-area-context',
          name: 'react-native-safe-area-context',
          version: '5.8.0',
          singleton: true,
          requiredVersion: '^5.5.2',
          assets: {
            js: {
              async: [],
              sync: [
                'node_modules_react-native-safe-area-context_src_index_tsx.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native-screens',
          name: 'react-native-screens',
          version: '4.26.2',
          singleton: true,
          requiredVersion: '^4.25.2',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-native-screens_src_index_tsx.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native-worklets',
          name: 'react-native-worklets',
          version: '0.12.1',
          singleton: true,
          requiredVersion: '^0.12.1',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-native-worklets_src_index_ts.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/Components/View/ReactNativeStyleAttributes',
          name: 'react-native/Libraries/Components/View/ReactNativeStyleAttributes',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/Core/setUpXHR',
          name: 'react-native/Libraries/Core/setUpXHR',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/Image/AssetRegistry',
          name: 'react-native/Libraries/Image/AssetRegistry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/Image/AssetSourceResolver',
          name: 'react-native/Libraries/Image/AssetSourceResolver',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/Image/resolveAssetSource',
          name: 'react-native/Libraries/Image/resolveAssetSource',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/NativeComponent/NativeComponentRegistry',
          name: 'react-native/Libraries/NativeComponent/NativeComponentRegistry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/NativeComponent/ViewConfigIgnore',
          name: 'react-native/Libraries/NativeComponent/ViewConfigIgnore',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/ReactNative/AppContainer',
          name: 'react-native/Libraries/ReactNative/AppContainer',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance',
          name: 'react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/ReactNative/RendererProxy',
          name: 'react-native/Libraries/ReactNative/RendererProxy',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/ReactPrivate/ReactNativePrivateInitializeCore',
          name: 'react-native/Libraries/ReactPrivate/ReactNativePrivateInitializeCore',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/ReactPrivate/ReactNativePrivateInterface',
          name: 'react-native/Libraries/ReactPrivate/ReactNativePrivateInterface',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/Renderer/shims/ReactFabric',
          name: 'react-native/Libraries/Renderer/shims/ReactFabric',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/StyleSheet/processColorArray',
          name: 'react-native/Libraries/StyleSheet/processColorArray',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/TurboModule/TurboModuleRegistry',
          name: 'react-native/Libraries/TurboModule/TurboModuleRegistry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/src/private/featureflags/ReactNativeFeatureFlags',
          name: 'react-native/src/private/featureflags/ReactNativeFeatureFlags',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native',
          name: 'react-native',
          version: '0.85.3',
          singleton: true,
          requiredVersion: '0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['vendors-node_modules_react-native_index_js.chunk.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-redux',
          name: 'react-redux',
          version: '9.3.0',
          singleton: true,
          requiredVersion: '^9.3.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-redux_dist_react-redux_legacy-esm_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react',
          name: 'react',
          version: '19.2.3',
          singleton: true,
          requiredVersion: '19.2.3',
          assets: {
            js: {
              async: [],
              sync: ['node_modules_react_index_js.chunk.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
      ],
      remotes: [],
      exposes: [
        {
          id: 'listApp:ListStack',
          name: 'ListStack',
          assets: {
            js: {
              sync: [
                'vendors-node_modules_pokedex_detail_src_index_ts-node_modules_graphql-request_build_entrypoin-878711.chunk.bundle',
                '__federation_expose_ListStack.chunk.bundle',
              ],
              async: [
                'vendors-node_modules_immer_dist_immer_legacy-esm_js-node_modules_reselect_dist_cjs_index_js.chunk.bundle',
              ],
            },
            css: { sync: [], async: [] },
          },
          path: './ListStack',
        },
      ],
    },
    partyApp: {
      id: 'partyApp',
      name: 'partyApp',
      metaData: {
        name: 'partyApp',
        type: 'app',
        buildInfo: { buildVersion: '0.0.1', buildName: 'Party' },
        remoteEntry: {
          name: 'partyApp.container.js.bundle',
          path: '',
          type: 'global',
        },
        types: { path: '', name: '', zip: '', api: '' },
        globalName: 'partyApp',
        pluginVersion: '2.9.0',
        publicPath: 'noop:///',
      },
      shared: [
        {
          id: 'partyApp:@pokedex/contracts',
          name: '@pokedex/contracts',
          version: '3.3.0',
          singleton: true,
          requiredVersion: '^3.3.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_pokedex_contracts_dist_index_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@pokedex/ui',
          name: '@pokedex/ui',
          version: '1.0.13',
          singleton: true,
          requiredVersion: '^1.0.13',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_pokedex_ui_src_index_ts.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@react-native/assets-registry/path-support',
          name: '@react-native/assets-registry/path-support',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@react-native/assets-registry/registry',
          name: '@react-native/assets-registry/registry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@react-native/normalize-colors',
          name: '@react-native/normalize-colors',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@react-native/virtualized-lists',
          name: '@react-native/virtualized-lists',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@react-navigation/native-stack',
          name: '@react-navigation/native-stack',
          version: '7.18.6',
          singleton: true,
          requiredVersion: '^7.18.6',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-navigation_native-stack_lib_module_index_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@react-navigation/native',
          name: '@react-navigation/native',
          version: '7.3.14',
          singleton: true,
          requiredVersion: '^7.3.1',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-navigation_native_lib_module_index_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@reduxjs/toolkit',
          name: '@reduxjs/toolkit',
          version: '2.12.0',
          singleton: true,
          requiredVersion: '^2.12.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_reduxjs_toolkit_dist_redux-toolkit_modern_mjs.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:nativewind',
          name: 'nativewind',
          version: '4.2.6',
          singleton: true,
          requiredVersion: '^4.2.6',
          assets: {
            js: {
              async: [],
              sync: ['node_modules_nativewind_dist_index_js.chunk.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native-reanimated',
          name: 'react-native-reanimated',
          version: '4.6.0',
          singleton: true,
          requiredVersion: '^4.6.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-native-reanimated_src_index_ts.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native-safe-area-context',
          name: 'react-native-safe-area-context',
          version: '5.8.0',
          singleton: true,
          requiredVersion: '^5.5.2',
          assets: {
            js: {
              async: [],
              sync: [
                'node_modules_react-native-safe-area-context_src_index_tsx.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native-screens',
          name: 'react-native-screens',
          version: '4.26.2',
          singleton: true,
          requiredVersion: '^4.25.2',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-native-screens_src_index_tsx.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native-worklets',
          name: 'react-native-worklets',
          version: '0.12.1',
          singleton: true,
          requiredVersion: '^0.12.1',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-native-worklets_src_index_ts.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/Components/View/ReactNativeStyleAttributes',
          name: 'react-native/Libraries/Components/View/ReactNativeStyleAttributes',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/Core/setUpXHR',
          name: 'react-native/Libraries/Core/setUpXHR',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/Image/AssetRegistry',
          name: 'react-native/Libraries/Image/AssetRegistry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/Image/AssetSourceResolver',
          name: 'react-native/Libraries/Image/AssetSourceResolver',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/Image/resolveAssetSource',
          name: 'react-native/Libraries/Image/resolveAssetSource',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/NativeComponent/NativeComponentRegistry',
          name: 'react-native/Libraries/NativeComponent/NativeComponentRegistry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/NativeComponent/ViewConfigIgnore',
          name: 'react-native/Libraries/NativeComponent/ViewConfigIgnore',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/ReactNative/AppContainer',
          name: 'react-native/Libraries/ReactNative/AppContainer',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance',
          name: 'react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/ReactNative/RendererProxy',
          name: 'react-native/Libraries/ReactNative/RendererProxy',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/ReactPrivate/ReactNativePrivateInitializeCore',
          name: 'react-native/Libraries/ReactPrivate/ReactNativePrivateInitializeCore',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/ReactPrivate/ReactNativePrivateInterface',
          name: 'react-native/Libraries/ReactPrivate/ReactNativePrivateInterface',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/Renderer/shims/ReactFabric',
          name: 'react-native/Libraries/Renderer/shims/ReactFabric',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/StyleSheet/processColorArray',
          name: 'react-native/Libraries/StyleSheet/processColorArray',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/TurboModule/TurboModuleRegistry',
          name: 'react-native/Libraries/TurboModule/TurboModuleRegistry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/src/private/featureflags/ReactNativeFeatureFlags',
          name: 'react-native/src/private/featureflags/ReactNativeFeatureFlags',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native',
          name: 'react-native',
          version: '0.85.3',
          singleton: true,
          requiredVersion: '0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['vendors-node_modules_react-native_index_js.chunk.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-redux',
          name: 'react-redux',
          version: '9.3.0',
          singleton: true,
          requiredVersion: '^9.3.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-redux_dist_react-redux_legacy-esm_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react',
          name: 'react',
          version: '19.2.3',
          singleton: true,
          requiredVersion: '19.2.3',
          assets: {
            js: {
              async: [],
              sync: ['node_modules_react_index_js.chunk.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
      ],
      remotes: [],
      exposes: [
        {
          id: 'partyApp:PartyStack',
          name: 'PartyStack',
          assets: {
            js: {
              sync: [
                'vendors-node_modules_pokedex_detail_src_index_ts.chunk.bundle',
                '__federation_expose_styles.chunk.bundle',
                '__federation_expose_PartyStack.chunk.bundle',
              ],
              async: [
                'vendors-node_modules_immer_dist_immer_legacy-esm_js-node_modules_reselect_dist_cjs_index_js.chunk.bundle',
              ],
            },
            css: { sync: [], async: [] },
          },
          path: './PartyStack',
        },
        {
          id: 'partyApp:partySlice',
          name: 'partySlice',
          assets: {
            js: {
              sync: ['__federation_expose_partySlice.chunk.bundle'],
              async: [
                'vendors-node_modules_immer_dist_immer_legacy-esm_js-node_modules_reselect_dist_cjs_index_js.chunk.bundle',
                'vendors-node_modules_pokedex_detail_src_index_ts.chunk.bundle',
                '__federation_expose_styles.chunk.bundle',
                '__federation_expose_PartyStack.chunk.bundle',
              ],
            },
            css: { sync: [], async: [] },
          },
          path: './partySlice',
        },
        {
          id: 'partyApp:styles',
          name: 'styles',
          assets: {
            js: {
              sync: [
                'vendors-node_modules_pokedex_detail_src_index_ts.chunk.bundle',
                '__federation_expose_styles.chunk.bundle',
                '__federation_expose_PartyStack.chunk.bundle',
              ],
              async: [
                'vendors-node_modules_immer_dist_immer_legacy-esm_js-node_modules_reselect_dist_cjs_index_js.chunk.bundle',
                'vendors-node_modules_pokedex_detail_src_index_ts.chunk.bundle',
                '__federation_expose_styles.chunk.bundle',
                '__federation_expose_PartyStack.chunk.bundle',
              ],
            },
            css: { sync: [], async: [] },
          },
          path: './styles',
        },
      ],
    },
  },
  android: {
    listApp: {
      id: 'listApp',
      name: 'listApp',
      metaData: {
        name: 'listApp',
        type: 'app',
        buildInfo: { buildVersion: '0.0.1', buildName: 'List' },
        remoteEntry: {
          name: 'listApp.container.js.bundle',
          path: '',
          type: 'global',
        },
        types: { path: '', name: '', zip: '', api: '' },
        globalName: 'listApp',
        pluginVersion: '2.9.0',
        publicPath: 'noop:///',
      },
      shared: [
        {
          id: 'listApp:@pokedex/contracts',
          name: '@pokedex/contracts',
          version: '3.3.0',
          singleton: true,
          requiredVersion: '^3.3.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_pokedex_contracts_dist_index_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@pokedex/ui',
          name: '@pokedex/ui',
          version: '1.0.13',
          singleton: true,
          requiredVersion: '^1.0.13',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_pokedex_ui_src_index_ts.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@react-native/assets-registry/path-support',
          name: '@react-native/assets-registry/path-support',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@react-native/assets-registry/registry',
          name: '@react-native/assets-registry/registry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@react-native/normalize-colors',
          name: '@react-native/normalize-colors',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@react-native/virtualized-lists',
          name: '@react-native/virtualized-lists',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@react-navigation/native-stack',
          name: '@react-navigation/native-stack',
          version: '7.18.6',
          singleton: true,
          requiredVersion: '^7.18.6',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-navigation_native-stack_lib_module_index_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@react-navigation/native',
          name: '@react-navigation/native',
          version: '7.3.14',
          singleton: true,
          requiredVersion: '^7.3.1',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-navigation_native_lib_module_index_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:@reduxjs/toolkit',
          name: '@reduxjs/toolkit',
          version: '2.12.0',
          singleton: true,
          requiredVersion: '^2.12.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_reduxjs_toolkit_dist_redux-toolkit_modern_mjs.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:nativewind',
          name: 'nativewind',
          version: '4.2.6',
          singleton: true,
          requiredVersion: '^4.2.6',
          assets: {
            js: {
              async: [],
              sync: ['node_modules_nativewind_dist_index_js.chunk.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native-reanimated',
          name: 'react-native-reanimated',
          version: '4.6.0',
          singleton: true,
          requiredVersion: '^4.6.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-native-reanimated_src_index_ts.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native-safe-area-context',
          name: 'react-native-safe-area-context',
          version: '5.8.0',
          singleton: true,
          requiredVersion: '^5.5.2',
          assets: {
            js: {
              async: [],
              sync: [
                'node_modules_react-native-safe-area-context_src_index_tsx.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native-screens',
          name: 'react-native-screens',
          version: '4.26.2',
          singleton: true,
          requiredVersion: '^4.25.2',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-native-screens_src_index_tsx.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native-worklets',
          name: 'react-native-worklets',
          version: '0.12.1',
          singleton: true,
          requiredVersion: '^0.12.1',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-native-worklets_src_index_ts.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/Components/View/ReactNativeStyleAttributes',
          name: 'react-native/Libraries/Components/View/ReactNativeStyleAttributes',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/Core/setUpXHR',
          name: 'react-native/Libraries/Core/setUpXHR',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/Image/AssetRegistry',
          name: 'react-native/Libraries/Image/AssetRegistry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/Image/AssetSourceResolver',
          name: 'react-native/Libraries/Image/AssetSourceResolver',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/Image/resolveAssetSource',
          name: 'react-native/Libraries/Image/resolveAssetSource',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/NativeComponent/NativeComponentRegistry',
          name: 'react-native/Libraries/NativeComponent/NativeComponentRegistry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/NativeComponent/ViewConfigIgnore',
          name: 'react-native/Libraries/NativeComponent/ViewConfigIgnore',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/ReactNative/AppContainer',
          name: 'react-native/Libraries/ReactNative/AppContainer',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance',
          name: 'react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/ReactNative/RendererProxy',
          name: 'react-native/Libraries/ReactNative/RendererProxy',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/ReactPrivate/ReactNativePrivateInitializeCore',
          name: 'react-native/Libraries/ReactPrivate/ReactNativePrivateInitializeCore',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/ReactPrivate/ReactNativePrivateInterface',
          name: 'react-native/Libraries/ReactPrivate/ReactNativePrivateInterface',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/Renderer/shims/ReactFabric',
          name: 'react-native/Libraries/Renderer/shims/ReactFabric',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/StyleSheet/processColorArray',
          name: 'react-native/Libraries/StyleSheet/processColorArray',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/Libraries/TurboModule/TurboModuleRegistry',
          name: 'react-native/Libraries/TurboModule/TurboModuleRegistry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native/src/private/featureflags/ReactNativeFeatureFlags',
          name: 'react-native/src/private/featureflags/ReactNativeFeatureFlags',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['listApp.container.js.bundle', 'index.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-native',
          name: 'react-native',
          version: '0.85.3',
          singleton: true,
          requiredVersion: '0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['vendors-node_modules_react-native_index_js.chunk.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react-redux',
          name: 'react-redux',
          version: '9.3.0',
          singleton: true,
          requiredVersion: '^9.3.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-redux_dist_react-redux_legacy-esm_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'listApp:react',
          name: 'react',
          version: '19.2.3',
          singleton: true,
          requiredVersion: '19.2.3',
          assets: {
            js: {
              async: [],
              sync: ['node_modules_react_index_js.chunk.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
      ],
      remotes: [],
      exposes: [
        {
          id: 'listApp:ListStack',
          name: 'ListStack',
          assets: {
            js: {
              sync: [
                'vendors-node_modules_pokedex_detail_src_index_ts-node_modules_graphql-request_build_entrypoin-878711.chunk.bundle',
                '__federation_expose_ListStack.chunk.bundle',
              ],
              async: [
                'vendors-node_modules_immer_dist_immer_legacy-esm_js-node_modules_reselect_dist_cjs_index_js.chunk.bundle',
              ],
            },
            css: { sync: [], async: [] },
          },
          path: './ListStack',
        },
      ],
    },
    partyApp: {
      id: 'partyApp',
      name: 'partyApp',
      metaData: {
        name: 'partyApp',
        type: 'app',
        buildInfo: { buildVersion: '0.0.1', buildName: 'Party' },
        remoteEntry: {
          name: 'partyApp.container.js.bundle',
          path: '',
          type: 'global',
        },
        types: { path: '', name: '', zip: '', api: '' },
        globalName: 'partyApp',
        pluginVersion: '2.9.0',
        publicPath: 'noop:///',
      },
      shared: [
        {
          id: 'partyApp:@pokedex/contracts',
          name: '@pokedex/contracts',
          version: '3.3.0',
          singleton: true,
          requiredVersion: '^3.3.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_pokedex_contracts_dist_index_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@pokedex/ui',
          name: '@pokedex/ui',
          version: '1.0.13',
          singleton: true,
          requiredVersion: '^1.0.13',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_pokedex_ui_src_index_ts.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@react-native/assets-registry/path-support',
          name: '@react-native/assets-registry/path-support',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@react-native/assets-registry/registry',
          name: '@react-native/assets-registry/registry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@react-native/normalize-colors',
          name: '@react-native/normalize-colors',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@react-native/virtualized-lists',
          name: '@react-native/virtualized-lists',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@react-navigation/native-stack',
          name: '@react-navigation/native-stack',
          version: '7.18.6',
          singleton: true,
          requiredVersion: '^7.18.6',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-navigation_native-stack_lib_module_index_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@react-navigation/native',
          name: '@react-navigation/native',
          version: '7.3.14',
          singleton: true,
          requiredVersion: '^7.3.1',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-navigation_native_lib_module_index_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:@reduxjs/toolkit',
          name: '@reduxjs/toolkit',
          version: '2.12.0',
          singleton: true,
          requiredVersion: '^2.12.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_reduxjs_toolkit_dist_redux-toolkit_modern_mjs.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:nativewind',
          name: 'nativewind',
          version: '4.2.6',
          singleton: true,
          requiredVersion: '^4.2.6',
          assets: {
            js: {
              async: [],
              sync: ['node_modules_nativewind_dist_index_js.chunk.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native-reanimated',
          name: 'react-native-reanimated',
          version: '4.6.0',
          singleton: true,
          requiredVersion: '^4.6.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-native-reanimated_src_index_ts.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native-safe-area-context',
          name: 'react-native-safe-area-context',
          version: '5.8.0',
          singleton: true,
          requiredVersion: '^5.5.2',
          assets: {
            js: {
              async: [],
              sync: [
                'node_modules_react-native-safe-area-context_src_index_tsx.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native-screens',
          name: 'react-native-screens',
          version: '4.26.2',
          singleton: true,
          requiredVersion: '^4.25.2',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-native-screens_src_index_tsx.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native-worklets',
          name: 'react-native-worklets',
          version: '0.12.1',
          singleton: true,
          requiredVersion: '^0.12.1',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-native-worklets_src_index_ts.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/Components/View/ReactNativeStyleAttributes',
          name: 'react-native/Libraries/Components/View/ReactNativeStyleAttributes',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/Core/setUpXHR',
          name: 'react-native/Libraries/Core/setUpXHR',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/Image/AssetRegistry',
          name: 'react-native/Libraries/Image/AssetRegistry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/Image/AssetSourceResolver',
          name: 'react-native/Libraries/Image/AssetSourceResolver',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/Image/resolveAssetSource',
          name: 'react-native/Libraries/Image/resolveAssetSource',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/NativeComponent/NativeComponentRegistry',
          name: 'react-native/Libraries/NativeComponent/NativeComponentRegistry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/NativeComponent/ViewConfigIgnore',
          name: 'react-native/Libraries/NativeComponent/ViewConfigIgnore',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/ReactNative/AppContainer',
          name: 'react-native/Libraries/ReactNative/AppContainer',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance',
          name: 'react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/ReactNative/RendererProxy',
          name: 'react-native/Libraries/ReactNative/RendererProxy',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/ReactPrivate/ReactNativePrivateInitializeCore',
          name: 'react-native/Libraries/ReactPrivate/ReactNativePrivateInitializeCore',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/ReactPrivate/ReactNativePrivateInterface',
          name: 'react-native/Libraries/ReactPrivate/ReactNativePrivateInterface',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/Renderer/shims/ReactFabric',
          name: 'react-native/Libraries/Renderer/shims/ReactFabric',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/StyleSheet/processColorArray',
          name: 'react-native/Libraries/StyleSheet/processColorArray',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/Libraries/TurboModule/TurboModuleRegistry',
          name: 'react-native/Libraries/TurboModule/TurboModuleRegistry',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native/src/private/featureflags/ReactNativeFeatureFlags',
          name: 'react-native/src/private/featureflags/ReactNativeFeatureFlags',
          version: '0.85.3',
          requiredVersion: '^0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['index.bundle', 'partyApp.container.js.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-native',
          name: 'react-native',
          version: '0.85.3',
          singleton: true,
          requiredVersion: '0.85.3',
          assets: {
            js: {
              async: [],
              sync: ['vendors-node_modules_react-native_index_js.chunk.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react-redux',
          name: 'react-redux',
          version: '9.3.0',
          singleton: true,
          requiredVersion: '^9.3.0',
          assets: {
            js: {
              async: [],
              sync: [
                'vendors-node_modules_react-redux_dist_react-redux_legacy-esm_js.chunk.bundle',
              ],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
        {
          id: 'partyApp:react',
          name: 'react',
          version: '19.2.3',
          singleton: true,
          requiredVersion: '19.2.3',
          assets: {
            js: {
              async: [],
              sync: ['node_modules_react_index_js.chunk.bundle'],
            },
            css: { async: [], sync: [] },
          },
          fallback: '',
        },
      ],
      remotes: [],
      exposes: [
        {
          id: 'partyApp:PartyStack',
          name: 'PartyStack',
          assets: {
            js: {
              sync: [
                'vendors-node_modules_pokedex_detail_src_index_ts.chunk.bundle',
                '__federation_expose_styles.chunk.bundle',
                '__federation_expose_PartyStack.chunk.bundle',
              ],
              async: [
                'vendors-node_modules_immer_dist_immer_legacy-esm_js-node_modules_reselect_dist_cjs_index_js.chunk.bundle',
              ],
            },
            css: { sync: [], async: [] },
          },
          path: './PartyStack',
        },
        {
          id: 'partyApp:partySlice',
          name: 'partySlice',
          assets: {
            js: {
              sync: ['__federation_expose_partySlice.chunk.bundle'],
              async: [
                'vendors-node_modules_immer_dist_immer_legacy-esm_js-node_modules_reselect_dist_cjs_index_js.chunk.bundle',
                'vendors-node_modules_pokedex_detail_src_index_ts.chunk.bundle',
                '__federation_expose_styles.chunk.bundle',
                '__federation_expose_PartyStack.chunk.bundle',
              ],
            },
            css: { sync: [], async: [] },
          },
          path: './partySlice',
        },
        {
          id: 'partyApp:styles',
          name: 'styles',
          assets: {
            js: {
              sync: [
                'vendors-node_modules_pokedex_detail_src_index_ts.chunk.bundle',
                '__federation_expose_styles.chunk.bundle',
                '__federation_expose_PartyStack.chunk.bundle',
              ],
              async: [
                'vendors-node_modules_immer_dist_immer_legacy-esm_js-node_modules_reselect_dist_cjs_index_js.chunk.bundle',
                'vendors-node_modules_pokedex_detail_src_index_ts.chunk.bundle',
                '__federation_expose_styles.chunk.bundle',
                '__federation_expose_PartyStack.chunk.bundle',
              ],
            },
            css: { sync: [], async: [] },
          },
          path: './styles',
        },
      ],
    },
  },
};
