// AUTO-GENERATED by tools/build-cdn.mjs for app version 2.0.0. Do not edit by hand.
//
// Which version of each remote the native build phases copied into the app, per platform. The
// copy itself, the signed bundles and the manifest, sits in the app at
// cdn/<platform>/<remote>/<version>/.

export const BUNDLED_VERSIONS: Record<string, Record<string, string>> = {
  ios: { listApp: '1.2.0', partyApp: '1.0.0' },
  android: { listApp: '1.2.0', partyApp: '1.0.0' },
};
